/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import account.Account;
import account.ReadFile;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
// import accounts.FileReader;


public class App {
    public static void main(String[] args) {
        //import the transaction file 
        // iterate over it and identify any new names
        //create any new account objects needed

        ReadFile reader = new ReadFile();
        reader.readFile();
        
    }
}

